# Generated by Django 4.1.7 on 2023-03-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_category_options_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.category'),
        ),
    ]
